name: recursive-dns

services:
  recursive-dns:
    image: ghcr.io/nergis0318/recursive-dns:latest
    container_name: recursive-dns
    restart: always
    ports:
      - 53:53/udp
      - 53:53/tcp
