[[zones]]
zone = "."
zone_type = "External"

[zones.stores]
type = "recursor"
roots = "/usr/share/dns/root.hints"
ns_cache_size = 1024
record_cache_size = 1048576
recursion_limit = 12
ns_recursion_limit = 16

[zones.stores.cache_policy.default]
positive_max_ttl = 86400

[zones.stores.cache_policy.A]
positive_max_ttl = 3600

[zones.stores.cache_policy.AAAA]
positive_max_ttl = 3600
