name: recursive-dns
services:
    recursive-dns:
        container_name: recursive-dns
        ports:
            - 53:53/udp
            - 53:53/tcp
        restart: always
        image: ghcr.io/devnergis/recursive-dns:latest
        
